run_steps:
  attack: True
  decode: True
  evaluate: True
  update: True


attack:
  original_test_dir: "CARLA_dataset/Spoof/Surrogate/merged_targated_Spoof_attack_images"
  original_label_file: "CARLA_dataset/Spoof/Surrogate/test_labels.txt"
  original_tracksheet: "CARLA_dataset/Spoof/Surrogate/test_track.csv"
  surrogate_model: "Trained_models/densenet161_surrogate_CARLA_Spoof.pth"
  output_dir: "perturbed_images_spoof_CARLA"

decode:
  decoded_output_dir: "decoded_traffic_spoof_CARLA"

evaluate:
  model_path: "Trained_models/CARLA_Spoof_og_final_model.h5"
  prediction_output_dir: "prediction_output_spoof_CARLA"

update:
  tracksheet_dir: "tracksheets_CARLA"
