run_steps:
  attack: True
  decode: True
  evaluate: True
  update: True


attack:
  original_test_dir: "dos_dataset/Mirgu_DoS_arbitrated_data/Surrogate/DoS_images_mirgu"
  original_label_file: "dos_dataset/Mirgu_DoS_arbitrated_data/Surrogate/test_labels.txt"
  original_tracksheet: "dos_dataset/Mirgu_DoS_arbitrated_data/Surrogate/test_track.csv"
  surrogate_model: "Trained_models/densenet161_surrogate_Mirgu_DoS.pth"
  output_dir: "perturbed_images_dos_mirgu"

decode:
  decoded_output_dir: "decoded_traffic_dos_mirgu"

evaluate:
  model_path: "Trained_models/Mirgu_DoS.h5"
  prediction_output_dir: "prediction_output_dos_mirgu"

update:
  tracksheet_dir: "tracksheets_mirgu"
